### PR TITLE
Added Ping

### PR DESCRIPTION
**Pull request by metalglove**
image

Added ping for each server. 
I recommend to use something different than a `ListItemView` to be more compatible with asynchronous operations..
For now, I implemented it as a working prototype. 

Please take a look.

### CODE REVIEW

**Review by Bowhza — APPROVED** [review]

**Comment by metalglove** [comment]
Don't merge it yet. Working on a small fix..

**Comment by Bowhza** [comment]
I would also suggest changing the -1 if the server couldn't be pinged to 'N/A' or something more understandable for the user

**Comment by metalglove** [comment]
> I would also suggest changing the -1 if the server couldn't be pinged to 'N/A' or something more understandable for the user

That is amongst one of the things I intended to do. :)

**Comment by Bowhza** [comment]
I was already familiar with WinForms and wanted to get a prototype out quickly. Using WPF would definitely be a better option, but I would have to spend more time getting familiar with it rather then developing the program.

**Comment by metalglove** [comment]
Ah ok. It is worth checking out ;-)

You can merge this as this bug is not something breaking really.

**Pull request merged**
