### PR TITLE
WPF REWRITE [WIP]

### LINKED ISSUE #7: Use proper IW4MAdmin API to retrieve servers
Instead of parsing the data from the HTML Panel Server List, use the `/instance` endpoint (see 
https://github.com/RaidMax/IW4MAdmin-Master/blob/master/README.md#instance).

This should clean up the code, improve performance and give us some extra information in a nicer format.

### LINKED ISSUE #8: Send UDP 'getInfo' message to game servers
The same thing the ingame Server Browser does. Can also measure roundtrip time instead of using ICMP to get Ping (many servers dont respond to ICMP, also this value should be more comparable to ingame latency as it actually goes through the game server).

With the Info response other information will be available too, such as number of bots, whether the Server is private or actually online...

### PR DESCRIPTION
**Pull request by metalglove**
We rewrite the launcher in WPF for better support of bindable functionality in the UI.

TODO:
- [x] Window
  - [x] ESC to close
  - [x] Draggable
  - [x] No window style 
- [x] Server browser
  - [x] Click to join server
    - [x] Copy IP to copy buffer
    - [x] Focus game window
    - [x] send disconnect before connect
  - [x] Sortable
    - [x] Default sort by occupation
    - [x] Sort by actual players not lexicographically
  - [x] Filterable
  - [x] Color text just like in the in game server browser
- [x] Check if launcher is up to date
  - [x] Guide user to update OR download newest release automatically
- [X] Update the ping functionality to getInfo (UDP)
- [x] Dialog window
  - [x] Error message boxes
  - [x] Error logging
- [x] Update readme to reflect changes

Future Updates:
  - [ ] Show servers who don't reply to ping if they have at least one player/bot
  - [ ] Private server icon
  - [ ] Indicate number of bots (when possible)

Closes #8 
Closes #7

### CODE REVIEW

**Comment by metalglove** [comment]
Initial WIP serverbrowser 
image

**Comment by metalglove** [comment]
image

**Comment by metalglove** [comment]
image

**Comment by metalglove** [comment]
image

**Comment by metalglove** [comment]
image

**Review by Bowhza — APPROVED** [review]

**Pull request merged**
